//! Mood-to-emoji mapping for NPC emotional state display.
//!
//! Converts freeform mood strings (generated by the LLM) into stylized
//! emoji for at-a-glance display in the sidebar and debug views.

/// Returns an emoji representing the given freeform mood string.
///
/// Uses case-insensitive substring matching to categorize LLM-generated
/// mood words into emoji. Checks more specific/intense emotions first
/// to avoid false matches on compound phrases like "restlessly angry".
///
/// Returns 🙂 as a fallback for unrecognized moods.
///
/// # Examples
///
/// ```
/// use parish_npc::mood::mood_emoji;
///
/// assert_eq!(mood_emoji("content"), "🙂");
/// assert_eq!(mood_emoji("angry"), "😡");
/// assert_eq!(mood_emoji("quietly contemplative"), "🤔");
/// ```
pub fn mood_emoji(mood: &str) -> &'static str {
    let m = mood.to_lowercase();

    // Negative/intense emotions (checked first for priority)
    if m.contains("angry") || m.contains("furious") || m.contains("enraged") || m.contains("irate")
    {
        return "😡";
    }
    if m.contains("afraid")
        || m.contains("fearful")
        || m.contains("terrified")
        || m.contains("scared")
    {
        return "😨";
    }
    if m.contains("anxious")
        || m.contains("nervous")
        || m.contains("worried")
        || m.contains("uneasy")
    {
        return "😰";
    }
    if m.contains("sad") || m.contains("grief") || m.contains("mournful") || m.contains("sorrowful")
    {
        return "😢";
    }
    if m.contains("melanchol")
        || m.contains("wistful")
        || m.contains("nostalgic")
        || m.contains("pensive")
    {
        return "😔";
    }
    if m.contains("irritat")
        || m.contains("frustrat")
        || m.contains("annoyed")
        || m.contains("grumpy")
    {
        return "😤";
    }
    if m.contains("suspicious") || m.contains("wary") || m.contains("distrustful") {
        return "🤨";
    }

    // Positive emotions
    if m.contains("joy")
        || m.contains("elated")
        || m.contains("ecstatic")
        || m.contains("delighted")
    {
        return "😄";
    }
    if m.contains("cheerful") || m.contains("jovial") || m.contains("merry") || m.contains("jolly")
    {
        return "😊";
    }
    if m.contains("friendly") || m.contains("welcoming") || m.contains("hospitable") {
        return "🤗";
    }
    if m.contains("amused") || m.contains("laughing") || m.contains("mirthful") {
        return "😆";
    }
    if m.contains("passionate") || m.contains("fervent") || m.contains("ardent") {
        return "🔥";
    }

    // Neutral/cognitive states
    if m.contains("contemplat")
        || m.contains("thoughtful")
        || m.contains("reflective")
        || m.contains("ponder")
    {
        return "🤔";
    }
    if m.contains("determined") || m.contains("resolute") || m.contains("steadfast") {
        return "💪";
    }
    if m.contains("alert")
        || m.contains("watchful")
        || m.contains("vigilant")
        || m.contains("attentive")
    {
        return "👀";
    }
    if m.contains("calm")
        || m.contains("serene")
        || m.contains("peaceful")
        || m.contains("tranquil")
    {
        return "😌";
    }
    if m.contains("content") || m.contains("satisfied") || m.contains("pleased") {
        return "🙂";
    }
    if m.contains("restless") || m.contains("agitated") || m.contains("fidgety") {
        return "😟";
    }
    if m.contains("tired") || m.contains("weary") || m.contains("exhausted") || m.contains("sleepy")
    {
        return "😴";
    }
    if m.contains("stoic")
        || m.contains("guarded")
        || m.contains("reserved")
        || m.contains("neutral")
    {
        return "😐";
    }
    if m.contains("curious") || m.contains("intrigued") || m.contains("interested") {
        return "🧐";
    }
    if m.contains("shy") || m.contains("bashful") || m.contains("embarrass") {
        return "😳";
    }
    if m.contains("proud") || m.contains("smug") || m.contains("self-satisfied") {
        return "😏";
    }
    if m.contains("surprised") || m.contains("astonished") || m.contains("shocked") {
        return "😮";
    }
    if m.contains("warm") {
        return "🤗";
    }

    // Fallback
    "🙂"
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_known_npc_moods() {
        // Moods from data/npcs.json
        assert_eq!(mood_emoji("content"), "🙂");
        assert_eq!(mood_emoji("determined"), "💪");
        assert_eq!(mood_emoji("contemplative"), "🤔");
        assert_eq!(mood_emoji("alert"), "👀");
        assert_eq!(mood_emoji("reflective"), "🤔");
        assert_eq!(mood_emoji("passionate"), "🔥");
        assert_eq!(mood_emoji("watchful"), "👀");
        assert_eq!(mood_emoji("restless"), "😟");
    }

    #[test]
    fn test_positive_emotions() {
        assert_eq!(mood_emoji("friendly"), "🤗");
        assert_eq!(mood_emoji("cheerful"), "😊");
        assert_eq!(mood_emoji("jovial"), "😊");
        assert_eq!(mood_emoji("joyful"), "😄");
        assert_eq!(mood_emoji("amused"), "😆");
        assert_eq!(mood_emoji("warm"), "🤗");
    }

    #[test]
    fn test_negative_emotions() {
        assert_eq!(mood_emoji("angry"), "😡");
        assert_eq!(mood_emoji("sad"), "😢");
        assert_eq!(mood_emoji("anxious"), "😰");
        assert_eq!(mood_emoji("afraid"), "😨");
        assert_eq!(mood_emoji("irritated"), "😤");
        assert_eq!(mood_emoji("frustrated"), "😤");
        assert_eq!(mood_emoji("melancholy"), "😔");
    }

    #[test]
    fn test_neutral_states() {
        assert_eq!(mood_emoji("calm"), "😌");
        assert_eq!(mood_emoji("stoic"), "😐");
        assert_eq!(mood_emoji("curious"), "🧐");
        assert_eq!(mood_emoji("tired"), "😴");
        assert_eq!(mood_emoji("surprised"), "😮");
        assert_eq!(mood_emoji("shy"), "😳");
        assert_eq!(mood_emoji("proud"), "😏");
        assert_eq!(mood_emoji("suspicious"), "🤨");
    }

    #[test]
    fn test_case_insensitive() {
        assert_eq!(mood_emoji("ANGRY"), "😡");
        assert_eq!(mood_emoji("Angry"), "😡");
        assert_eq!(mood_emoji("Content"), "🙂");
        assert_eq!(mood_emoji("CHEERFUL"), "😊");
    }

    #[test]
    fn test_compound_moods() {
        assert_eq!(mood_emoji("quietly content"), "🙂");
        assert_eq!(mood_emoji("somewhat anxious"), "😰");
        assert_eq!(mood_emoji("deeply contemplative"), "🤔");
        assert_eq!(mood_emoji("warmly friendly"), "🤗");
    }

    #[test]
    fn test_priority_ordering() {
        // More specific/intense emotions should win over milder ones
        assert_eq!(mood_emoji("restlessly angry"), "😡");
        assert_eq!(mood_emoji("anxiously sad"), "😰");
    }

    #[test]
    fn test_fallback_for_unknown() {
        assert_eq!(mood_emoji("xyzzy"), "🙂");
        assert_eq!(mood_emoji(""), "🙂");
        assert_eq!(mood_emoji("indescribable"), "🙂");
    }

    #[test]
    fn test_every_emoji_reachable() {
        // Ensure every distinct emoji in the mapping is reachable
        let cases = vec![
            ("angry", "😡"),
            ("afraid", "😨"),
            ("anxious", "😰"),
            ("sad", "😢"),
            ("melancholy", "😔"),
            ("irritated", "😤"),
            ("suspicious", "🤨"),
            ("joyful", "😄"),
            ("cheerful", "😊"),
            ("friendly", "🤗"),
            ("amused", "😆"),
            ("passionate", "🔥"),
            ("contemplative", "🤔"),
            ("determined", "💪"),
            ("alert", "👀"),
            ("calm", "😌"),
            ("content", "🙂"),
            ("restless", "😟"),
            ("tired", "😴"),
            ("stoic", "😐"),
            ("curious", "🧐"),
            ("shy", "😳"),
            ("proud", "😏"),
            ("surprised", "😮"),
        ];
        for (mood, expected) in cases {
            assert_eq!(
                mood_emoji(mood),
                expected,
                "mood '{}' should map to {}",
                mood,
                expected
            );
        }
    }
}
