/**
 * Contract test: types.ts field-name parity with Rust serde payloads.
 *
 * Reads types-manifest.json (the ground-truth field list generated by
 * inspecting Rust structs) and asserts that every required field appears
 * in the corresponding TypeScript interface in types.ts.
 *
 * Companion Rust test: parish/crates/parish-core/tests/ipc_field_parity.rs
 * serializes representative struct instances and asserts their JSON keys
 * match the same manifest — so drift in either direction fails CI.
 *
 * TD-053 / #1202
 */

// @vitest-environment node

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

// Resolve paths relative to this test file's directory.
const DIR = new URL('.', import.meta.url).pathname;

const manifestPath = resolve(DIR, 'types-manifest.json');
const typesPath = resolve(DIR, 'types.ts');

// Load fixtures once.
const manifest: Record<string, string[]> = JSON.parse(
	readFileSync(manifestPath, 'utf-8'),
);
const typesSource: string = readFileSync(typesPath, 'utf-8');

/**
 * Extract all field names declared in a TypeScript `interface Foo { … }` block.
 *
 * Strategy: find the interface body by tracking brace depth, then scan each
 * line for a `fieldName:` or `fieldName?:` pattern.  We intentionally keep
 * this simple (regex over source text) to avoid a heavy TS compiler dep.
 * The regex is conservative: it matches only identifier characters and
 * underscores, which is exactly the snake_case format the serde fields use.
 */
function extractInterfaceFields(
	source: string,
	interfaceName: string,
): Set<string> {
	// Find the opening `interface Foo {` (possibly with `export`).
	const headerRe = new RegExp(
		`(?:^|\\n)\\s*(?:export\\s+)?interface\\s+${interfaceName}\\b[^{]*\\{`,
	);
	const match = headerRe.exec(source);
	if (!match) {
		return new Set();
	}

	// Walk forward from the `{`, tracking brace depth to find the closing `}`.
	let depth = 0;
	const start = match.index + match[0].length - 1; // points at the `{`
	let end = -1;
	for (let i = start; i < source.length; i++) {
		if (source[i] === '{') depth++;
		else if (source[i] === '}') {
			depth--;
			if (depth === 0) {
				end = i;
				break;
			}
		}
	}

	if (end === -1) {
		return new Set();
	}

	const body = source.slice(start + 1, end);

	// Match `fieldName:` or `fieldName?:` at the start of a (possibly-indented)
	// line.  The field name is `[a-zA-Z_][a-zA-Z0-9_]*`.
	const fieldRe = /^\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*\??:/gm;
	const fields = new Set<string>();
	let m: RegExpExecArray | null;
	while ((m = fieldRe.exec(body)) !== null) {
		fields.add(m[1]);
	}
	return fields;
}

// Skip the $comment key that is documentation only.
const interfaceNames = Object.keys(manifest).filter((k) => !k.startsWith('$'));
const exactInterfaceNames = new Set([
	'WorldSnapshot',
	'PlayerTaskSnapshot',
	'DemoContextSnapshot',
	'ReconnectState',
]);

describe('types.ts ↔ Rust serde field-name parity (TD-053)', () => {
	it('types-manifest.json is non-empty', () => {
		expect(interfaceNames.length).toBeGreaterThan(0);
	});

	it('types.ts source is readable', () => {
		expect(typesSource.length).toBeGreaterThan(0);
	});

	for (const iface of interfaceNames) {
		it(`${iface}: fields match the manifest contract`, () => {
			const required = manifest[iface];
			const declared = extractInterfaceFields(typesSource, iface);

			expect(
				declared.size,
				`interface ${iface} not found in types.ts — was it renamed or moved?`,
			).toBeGreaterThan(0);

			const missing = required.filter((f) => !declared.has(f));
			const extra = [...declared].filter((f) => !required.includes(f));
			expect(
				missing,
				`interface ${iface} is missing field(s) from the Rust manifest: ` +
					missing.map((f) => `"${f}"`).join(', ') +
					'. Add the field to types.ts or update types-manifest.json.',
			).toHaveLength(0);
			if (exactInterfaceNames.has(iface)) {
				expect(
					extra,
					`interface ${iface} has field(s) missing from the Rust manifest: ` +
						extra.map((f) => `"${f}"`).join(', ') +
						'. Add the field to types-manifest.json or remove it from types.ts.',
				).toHaveLength(0);
			}
		});
	}
});
